#  Copyright 2023 The Zero Saver Authors. All Rights Reserved.
#
#  This file is part of Zero Saver.
#
#  Zero Saver is free software: you can redistribute it and/or modify it under
#  the terms of the GNU General Public License as published by the Free Software
#  Foundation, either version 3 of the License, or (at your option) any later
#  version.
#
#  Zero Saver is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
#  A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with
#  Zero Saver. If not, see <https://www.gnu.org/licenses/>.
# pylint: disable=missing-module-docstring
# pylint: disable=missing-class-docstring
# pylint: disable=redefined-outer-name
import pytest_cases


class StashCase:

  @pytest_cases.case(tags=['Stash', 'Well-Formed'])
  def stash_live_save(self):
    return {
        'chest_4': {
            'items': [
                {
                    'item': 'car_battery',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 144.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'bulb',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'bulb',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'bulb',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'bulb',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'bulb',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'bulb',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'bulb',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'bulb',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'bulb',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'hammer',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'hammer',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'metal_pipe',
                    'quantity': 4.0,
                    'x': 48.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'metal_pipe',
                    'quantity': 2.0,
                    'x': 64.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'multi_plug',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'multi_plug',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'multi_plug',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'multi_plug',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'multi_plug',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'multi_plug',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'power_outlet',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'power_outlet',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'power_outlet',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'power_outlet',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'power_outlet',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'power_outlet',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'power_outlet',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'power_outlet',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'power_outlet',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'power_outlet',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'power_outlet',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'power_outlet',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'relay',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'relay',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'relay',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'relay',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'relay',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'relay',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'relay',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'relay',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'relay',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'screw_nut',
                    'quantity': 6.0,
                    'x': 0.0,
                    'y': 96.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'soap',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 96.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'soap',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 96.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'soap',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 96.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'soap',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 96.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'wires',
                    'quantity': 2.0,
                    'x': 32.0,
                    'y': 112.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'wires',
                    'quantity': 2.0,
                    'x': 48.0,
                    'y': 112.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'wires',
                    'quantity': 2.0,
                    'x': 64.0,
                    'y': 112.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'wrench',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 112.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'wrench',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 112.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'wrench',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 112.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'wrench',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 128.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'wrench',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 128.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'dutch_tape',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 128.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'dutch_tape',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 128.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'dutch_tape',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 144.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'dutch_tape',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 160.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'dutch_tape',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 160.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'dutch_tape',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 160.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'dutch_tape',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 144.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_material',
                    'quantity': 30.0,
                    'x': 112.0,
                    'y': 144.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_material',
                    'quantity': 21.0,
                    'x': 0.0,
                    'y': 160.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
            ]
        },
        'chest_3': {
            'items': [
                {
                    'item': 'injector5',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_med',
                    'quantity': 16.0,
                    'x': 16.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_med',
                    'quantity': 20.0,
                    'x': 80.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_med',
                    'quantity': 20.0,
                    'x': 64.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_med',
                    'quantity': 20.0,
                    'x': 48.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_med',
                    'quantity': 20.0,
                    'x': 32.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_med',
                    'quantity': 20.0,
                    'x': 16.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_food',
                    'quantity': 10.0,
                    'x': 0.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_food',
                    'quantity': 20.0,
                    'x': 112.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector_vuoto',
                    'quantity': 4.0,
                    'x': 96.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector_vuoto',
                    'quantity': 4.0,
                    'x': 80.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector_vuoto',
                    'quantity': 4.0,
                    'x': 64.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector_vuoto',
                    'quantity': 4.0,
                    'x': 48.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'bandage_sterilizzata',
                    'quantity': 4.0,
                    'x': 32.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'pills_anti_rad',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'pills_anti_rad',
                    'quantity': 4.0,
                    'x': 0.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'pills_anti_rad',
                    'quantity': 4.0,
                    'x': 112.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'medikit_3',
                    'quantity': 2.0,
                    'x': 96.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'medikit_long',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'medikit_1',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'medikit_1',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'medikit_1',
                    'quantity': 3.0,
                    'x': 32.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector7',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector2',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector3',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector3',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector1',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector1',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector1',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector1',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector1',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
            ]
        },
        'chest_2': {
            'items': [
                {
                    'x': 0.0,
                    'quantity': 1.0,
                    'durability': 71.0,
                    'ammo_id': 'ammo_762x54R_snb',
                    'ammo_quantity': 0.0,
                    'item': 'svd',
                    'weapon_fire_mode': 'semi_automatic',
                    'y': 0.0,
                    'mods': {
                        'barrel': 'no_item',
                        'att_1': 'no_item',
                        'magazine': 'mod_svd_magazine_1',
                        'att_3': 'no_item',
                        'stock': 'mod_svd_stock_2',
                        'handguard': 'mod_svd_handguard_3',
                        'brake': 'no_item',
                        'att_2': 'no_item',
                        'att_4': 'no_item',
                        'grip': 'no_item',
                        'scope': 'mod_scope_holosun',
                    },
                    'rotation': 0.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_verde',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_verde',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_verde',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_verde',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'drill',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'drill',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_blu',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_blu',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_blu',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_blu',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_blu',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_blu',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_blu',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_blu',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_blu',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_blu',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_blu',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_red',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_red',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_red',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_red',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'cristallo_red',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'smartphone',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'wrench',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'screwdriver',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'screwdriver',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
            ]
        },
        'chest_0': {
            'items': [
                {
                    'item': 'ammo_762x54R_snb',
                    'quantity': 50.0,
                    'x': 112.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'ammo_762x39_hp',
                    'quantity': 48.0,
                    'x': 80.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'ammo_762x39_hp',
                    'quantity': 120.0,
                    'x': 0.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 1.0,
                },
                {
                    'item': 'ammo_762x54R',
                    'quantity': 50.0,
                    'x': 32.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'ammo_762x54R',
                    'quantity': 23.0,
                    'x': 48.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'ammo_762x54R_snb',
                    'quantity': 25.0,
                    'x': 64.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'ammo_762x54R_snb',
                    'quantity': 50.0,
                    'x': 80.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 1.0,
                },
                {
                    'item': 'armor_m_2',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 0.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'armor_loner_2',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'armor_arman',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'backpack7',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'backpack3',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 32.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'key_oil_green',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'repair_weapon3_high',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'repair_weapon2_high',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'repair_weapon2_low',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'repair_weapon2_low',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'mod_ar15_barrel_2',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'mod_ar15_magazine_30_2',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'mod_scope_pso',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'x': 32.0,
                    'quantity': 1.0,
                    'durability': 67.0,
                    'ammo_id': 'ammo_762x39',
                    'ammo_quantity': 0.0,
                    'item': 'akm',
                    'weapon_fire_mode': 'automatic',
                    'y': 80.0,
                    'mods': {
                        'barrel': 'mod_ak74_barrel_1',
                        'att_1': 'no_item',
                        'magazine': 'mod_ak74_magazine_s_3',
                        'att_3': 'no_item',
                        'stock': 'mod_ar15_stock_3',
                        'handguard': 'mod_ak_wooden_grip_rail',
                        'brake': 'no_item',
                        'att_2': 'no_item',
                        'att_4': 'no_item',
                        'grip': 'mod_rpk_grip',
                        'scope': 'mod_ak74_sight_1',
                    },
                    'rotation': 0.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'x': 0.0,
                    'quantity': 1.0,
                    'durability': 64.0,
                    'ammo_id': 'ammo_762x39_bp',
                    'ammo_quantity': 0.0,
                    'item': 'akm',
                    'weapon_fire_mode': 'automatic',
                    'y': 112.0,
                    'mods': {
                        'barrel': 'mod_ak74_barrel_1',
                        'att_1': 'mod_torch_1',
                        'magazine': 'mod_ak74_magazine_pmag',
                        'att_3': 'no_item',
                        'stock': 'mod_ar15_stock_green',
                        'handguard': 'mod_ak74_handguard_3',
                        'brake': 'no_item',
                        'att_2': 'no_item',
                        'att_4': 'no_item',
                        'grip': 'mod_ak74_grip_2_y',
                        'scope': 'mod_scope_kobra',
                    },
                    'rotation': 0.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'x': 64.0,
                    'quantity': 1.0,
                    'durability': 71.0,
                    'ammo_id': 'ammo_762x39',
                    'ammo_quantity': 0.0,
                    'item': 'akm',
                    'weapon_fire_mode': 'automatic',
                    'y': 112.0,
                    'mods': {
                        'barrel': 'mod_ak74_barrel_1',
                        'att_1': 'no_item',
                        'magazine': 'mod_ak74_magazine_s_2',
                        'att_3': 'no_item',
                        'stock': 'mod_ak74_stock_2',
                        'handguard': 'mod_ak_wooden_grip_rail',
                        'brake': 'no_item',
                        'att_2': 'no_item',
                        'att_4': 'no_item',
                        'grip': 'mod_rpk_grip',
                        'scope': 'mod_ak74_sight_1',
                    },
                    'rotation': 0.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'x': 0.0,
                    'quantity': 1.0,
                    'durability': 100.0,
                    'ammo_id': 'ammo_762x54R',
                    'ammo_quantity': 0.0,
                    'item': 'mosin',
                    'weapon_fire_mode': 'bolt_action',
                    'y': 144.0,
                    'mods': {
                        'barrel': 'no_item',
                        'att_1': 'no_item',
                        'magazine': 'no_item',
                        'att_3': 'no_item',
                        'stock': 'mod_mosin_stock_1',
                        'handguard': 'no_item',
                        'brake': 'no_item',
                        'att_2': 'no_item',
                        'att_4': 'no_item',
                        'grip': 'no_item',
                        'scope': 'mod_scope_pu',
                    },
                    'rotation': 0.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'mod_ak74_handguard_3',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 144.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
            ]
        },
        'chest_1': {
            'items': [
                {
                    'item': 'nail',
                    'quantity': 25.0,
                    'x': 0.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_material',
                    'quantity': 9.0,
                    'x': 112.0,
                    'y': 96.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'screwdriver',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 96.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'screwdriver',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 96.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'screwdriver',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 96.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_weapon',
                    'quantity': 34.0,
                    'x': 32.0,
                    'y': 96.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_material',
                    'quantity': 30.0,
                    'x': 16.0,
                    'y': 96.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_material',
                    'quantity': 30.0,
                    'x': 0.0,
                    'y': 96.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_food',
                    'quantity': 12.0,
                    'x': 112.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_food',
                    'quantity': 20.0,
                    'x': 96.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_ammo',
                    'quantity': 18.0,
                    'x': 80.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_ammo',
                    'quantity': 100.0,
                    'x': 64.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'scrap_ammo',
                    'quantity': 100.0,
                    'x': 48.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'acqua_ossigenata',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'acqua_ossigenata',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'acqua_ossigenata',
                    'quantity': 1.0,
                    'x': 0.0,
                    'y': 80.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'acqua_ossigenata',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'acqua_ossigenata',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'wires',
                    'quantity': 2.0,
                    'x': 80.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'wires',
                    'quantity': 2.0,
                    'x': 64.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'wires',
                    'quantity': 2.0,
                    'x': 48.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector_vuoto',
                    'quantity': 4.0,
                    'x': 32.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector_vuoto',
                    'quantity': 4.0,
                    'x': 16.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector_vuoto',
                    'quantity': 4.0,
                    'x': 0.0,
                    'y': 64.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'injector_vuoto',
                    'quantity': 4.0,
                    'x': 112.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'soap',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'soap',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'soap',
                    'quantity': 1.0,
                    'x': 64.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'soap',
                    'quantity': 1.0,
                    'x': 48.0,
                    'y': 48.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'nail',
                    'quantity': 25.0,
                    'x': 112.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'nail',
                    'quantity': 25.0,
                    'x': 96.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'nail',
                    'quantity': 25.0,
                    'x': 80.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'nail',
                    'quantity': 25.0,
                    'x': 64.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'battery',
                    'quantity': 2.0,
                    'x': 64.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'battery',
                    'quantity': 4.0,
                    'x': 48.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'battery',
                    'quantity': 4.0,
                    'x': 32.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'battery',
                    'quantity': 4.0,
                    'x': 16.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'battery',
                    'quantity': 4.0,
                    'x': 0.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'usb',
                    'quantity': 1.0,
                    'x': 80.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'usb',
                    'quantity': 1.0,
                    'x': 96.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'usb',
                    'quantity': 1.0,
                    'x': 112.0,
                    'y': 0.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'usb',
                    'quantity': 1.0,
                    'x': 16.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
                {
                    'item': 'usb',
                    'quantity': 1.0,
                    'x': 32.0,
                    'y': 16.0,
                    'rotation': 0.0,
                    'durability': 100.0,
                    'seen': 1.0,
                    'created_from_player': 0.0,
                },
            ]
        },
        'Storage': {'slot now': 5.0},
    }

  @pytest_cases.case(tags=['Stash', 'Well-Formed'])
  def stash_empty(self):
    return {}


class ChestCase:

  @pytest_cases.case(tags=['Chest', 'Well-Formed'])
  def chest_live_save(self):
    return [{
        'item': 'nail',
        'quantity': 25.0,
        'x': 0.0,
        'y': 16.0,
        'rotation': 0.0,
        'durability': 100.0,
        'seen': 1.0,
        'created_from_player': 0.0,
    }]

  @pytest_cases.case(tags=['Chest', 'Well-Formed'])
  def chest_empty(self):
    return []
